# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: qr243vbi.NekoBox
PackageVersion: 5.10.3
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
ProductCode: NekoBox
ReleaseDate: 2026-01-26
AppsAndFeaturesEntries:
- ProductCode: NekoBox
  DisplayName: NekoBox
  Publisher: qr243vbi
InstallModes:
  - silentWithProgress
  - silent
InstallerSwitches:
  Silent: "/S /NOSCRIPT=1 /WINGET=1"
  SilentWithProgress: "/S /NOSCRIPT=1 /WINGET=1"
InstallationMetadata:
  DefaultInstallLocation: '%AppData%\NekoBox'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/qr243vbi/nekobox/releases/download/5.10.3/nekobox-5.10.3-windows32-installer.exe
  InstallerSha256: OldSha32
- Architecture: x64
  InstallerUrl: https://github.com/qr243vbi/nekobox/releases/download/5.10.3/nekobox-5.10.3-windows64-installer.exe
  InstallerSha256: OldSha64
- Architecture: arm64
  InstallerUrl: https://github.com/qr243vbi/nekobox/releases/download/5.10.3/nekobox-5.10.3-windows-arm64-installer.exe
  InstallerSha256: OldShaArm
ManifestType: installer
ManifestVersion: 1.10.0